services:
  db:
    image: mysql:8.1
    container_name: contaia_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1122511176MvF.
      MYSQL_DATABASE: bsproyecto
      MYSQL_USER: root
      MYSQL_PASSWORD: 1122511176MvF.
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p1122511176MvF." ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: contaia_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://root:1122511176MvF.@db:3306/bsproyecto
      APP_ENV: development
      DEBUG: "true"
      CORS_ORIGINS: http://localhost:5173,http://127.0.0.1:5173
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: contaia_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:8000/api/v1
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

volumes:
  mysql_data:
