/**
 * Roles del sistema y permisos por defecto
 */

import { PERMISSIONS, ALL_PERMISSION_CODES } from "./permissions.js";

export const ROLES = {
  ADMINISTRADOR: "Administrador",
  CONTADOR: "Contador",
  EMPLEADO: "Empleado",
  GERENTE: "Gerente",
};

export const ALL_ROLES = Object.values(ROLES);

export { PERMISSIONS, ALL_PERMISSION_CODES };

export const ROLE_PERMISSIONS = {
  [ROLES.ADMINISTRADOR]: ALL_PERMISSION_CODES,
  [ROLES.CONTADOR]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CLIENTS_READ, PERMISSIONS.CLIENTS_WRITE,
    PERMISSIONS.SUPPLIERS_READ, PERMISSIONS.SUPPLIERS_WRITE,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVOICES_READ, PERMISSIONS.INVOICES_WRITE,
    PERMISSIONS.INCOME_READ, PERMISSIONS.INCOME_WRITE,
    PERMISSIONS.EXPENSES_READ, PERMISSIONS.EXPENSES_WRITE,
    PERMISSIONS.REPORTS_READ, PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.AI_USE,
  ],
  [ROLES.EMPLEADO]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CLIENTS_READ, PERMISSIONS.CLIENTS_WRITE,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVOICES_READ, PERMISSIONS.INVOICES_WRITE,
    PERMISSIONS.INCOME_READ,
    PERMISSIONS.EXPENSES_READ,
    PERMISSIONS.AI_USE,
  ],
  [ROLES.GERENTE]: [
    PERMISSIONS.DASHBOARD_READ,
    PERMISSIONS.CLIENTS_READ,
    PERMISSIONS.SUPPLIERS_READ,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVOICES_READ,
    PERMISSIONS.INCOME_READ,
    PERMISSIONS.EXPENSES_READ,
    PERMISSIONS.REPORTS_READ, PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.AI_USE,
  ],
};

export function getPermissionsForRole(role) {
  return ROLE_PERMISSIONS[role] || [];
}
